### ISSUE TITLE
关于该仓库所属组织的一些问题

### ISSUE THREAD

**Issue by asahiqin** [ST-Robot/bulletin#1]
很抱歉打扰到各位，提出这个issue是想询问一些问题
![Screenshot_2024-08-27-22-57-14-48_c1ebbaff44ba152fb7f7c2e1f7129fd1.jpg](https://github.com/user-attachments/assets/eab0f534-96f4-469b-b8e6-c65918530b56)

这个截图来在于我所在学校的宣传视频，其中名称与图标设计均与本项目所属组织完全一致  

所以简单来讲就是，我不清楚二位贡献者(@ssXue与@MRNIU )是否曾参加过陕西咸阳实验高中机器人社团，如果正是如此，那么由衷的感谢二位学长以及其他学长设计出来的徽标以及解决特色的宣传视频

但假如二位不是陕西咸阳实验中学毕业的话，那么我觉得	有必要改掉宣传视频里的部分徽标及名称

再次对我的贸然打扰表示抱歉，愿二位贡献者能学业有成

**Comment by ssXue** [comment]
这是当时对于社团相关资料的留存，由于忙于生计早已废弃，如有需要可以在社团群内联系我（13届管理员）

**Comment by asahiqin** [comment]
> 这是当时对于社团相关资料的留存，由于忙于生计早已废弃，如有需要可以在社团群内联系我（13届管理员）

好吧，其实我好奇的是这个组织的所有权，因为两个公开仓库的最后一次提交都在五年前，我也在想要不要重新把这个组织用起来


以及社团群，我没在群里，赵老师让我加群，结果没通过，就很神奇


总之谢谢您的回复

**Comment by MRNIU** [comment]
@asahiqin hi asahiqin, 已经拉了 @suarez9999 作为 owner，如果需要进 org 请联系 ta
